[build]
  # Build command (if any dependencies need to be built)
  command = "npm install"
  
  # Functions directory
  functions = "netlify/functions"
  
  # No static publish directory for backend
  publish = "."

[build.environment]
  NODE_VERSION = "18"

# Environment variables for production
[build.processing]
  skip_processing = true

# Redirect API routes to specific functions
[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/health"
  status = 200

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/health"
  status = 200

[[redirects]]
  from = "/api/bookings/create"
  to = "/.netlify/functions/create-booking"
  status = 200

[[redirects]]
  from = "/api/bookings/create-payment"
  to = "/.netlify/functions/create-payment"
  status = 200

[[redirects]]
  from = "/api/bookings/add-users"
  to = "/.netlify/functions/bookings"
  status = 200
  
[[redirects]]
  from = "/api/bookings/confirm-payment"
  to = "/.netlify/functions/bookings"
  status = 200

# Catch-all for other API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/bookings"
  status = 200

# Headers for CORS
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"